# Generated by Django 5.2.7 on 2025-11-24 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('audio', 'Audio'), ('interactive', 'Interactive'), ('quiz', 'Quiz')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to='lesson_audio/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='lesson_thumbnails/')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=10)),
                ('is_required', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'slug')},
            },
        ),
    ]
