# Generated by Django 5.2.7 on 2025-11-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.PositiveIntegerField(default=100, help_text='Capacidad máxima de estudiantes')),
                ('classrooms', models.PositiveIntegerField(default=5, help_text='Número de aulas disponibles')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de Aprendizaje',
                'verbose_name_plural': 'Centros de Aprendizaje',
                'ordering': ['-created_at'],
            },
        ),
    ]
