# Generated by Django 5.2.7 on 2025-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('native_name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('difficulty_level', models.PositiveIntegerField(default=1, help_text='1=Easy, 5=Very Hard')),
                ('description', models.TextField(blank=True)),
                ('total_speakers', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
